name: SwordsGame
main: me.coolblinger.swordsgame.SwordsGame
autthor: coolblinger
version: 1.2.3
description: >
  A GunGame like PvP game for Minecraft.
commands:
   sg:
      description: Main command for SwordsGame
      usage: /<command>
      aliases: swordsgame
permissions:
   swordsgame.*:
      description: Lets people define arenas and play them
      children:
         swordsgame.define: true
         swordsgame.play: true
   swordsgame.define:
      description: Define/remove arenas and be able to modify existing arenas
      default: op
   swordsgame.play:
      description: Play SwordsGame and list games/arenas
      default: true