name: SwordsGame
main: me.coolblinger.swordsgame.SwordsGame
autthor: coolblinger
version: 1.0.1
description: >
  A GunGame like PvP game for Minecraft.
commands:
   sg:
      description: Main command for SwordsGame
      usage: /<command>
      aliases: swordsgame